name: CI

# Запускается при push или pull_request в соответствующие ветки
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Работы
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # appleboy/ssh-action — это действие, которое
      # позволяет выполнять SSH-команды на удалённых
      # серверах. Оно часто используется для
      # автоматизации развертываний приложений на
      # удалённых серверах через SSH с использованием
      # Jenkins, Travis CI и других CI/CD систем.
      - name: Deploy to FirstVDS via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |

            git clone https://github.com/force278/bibintoApp-frontend.git

            rsync -avz --delete bibintoApp-frontend/web/ /home/bibinto_front/

            bash front.sh
