name: CI

# Запускается при push или pull_request в соответствующие ветки
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Работы
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Стандартная GitHub Action для извлечения кода из репозитория
      - name: Checkout master
        uses: actions/checkout@v3

      # Настройка SSH для доступа к приватному репозиторию
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # appleboy/ssh-action — это действие, которое
      # позволяет выполнять SSH-команды на удалённых
      # серверах. Оно часто используется для
      # автоматизации развертываний приложений на
      # удалённых серверах через SSH с использованием
      # Jenkins, Travis CI и других CI/CD систем.
      - name: Deploy to FirstVDS via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |

            # завершить скрипт при ошибке
            set -e  

            # Перейти в домашний каталог
            cd

            # Клонировать репозиторий; удалить директорию, если она уже существует
            if [ -d "bibintoApp-frontend" ]; then
              rm -rf bibintoApp-frontend
            fi

            git clone git@github.com:force278/bibintoApp-frontend.git

            # Синхронизировать файлы
            rsync -avz bibintoApp-frontend/ /home/bibinto_front/

            # Запустить скрипт
            chmod +x front.sh  # сделать скрипт исполняемым, если это необходимо
            bash front.sh
            echo "Деплой успешен"
