name: CI

# Запускается при push или pull_request в соответствующие ветки
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Работы
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # actions/checkout — это стандартная GitHub Action,
      # которая используется для извлечения (checkout) кода
      # из репозитория. Она позволяет вам получить доступ к
      # коду вашего проекта, чтобы вы могли выполнять
      # сборку, тестирование или любые другие действия с
      # ним в ходе рабочего процесса (workflow).

      # @v3 — это версия действия. В данном случае это
      # третья версия actions/checkout. Указывая версию,
      # вы обеспечиваете стабильность и предсказуемость,
      # так как не будете автоматически получать обновления
      # (возможно, с изменением поведения) при изменении
      # более новых версий этого действия.

      # Когда вы добавляете этот шаг в ваш файл конфигурации
      # рабочего процесса GitHub Actions, вы обеспечиваете,
      # что код вашего репозитория будет доступен для
      # дальнейших шагов в процессе сборки или тестирования.
      - name: Checkout master
        uses: actions/checkout@v3
      # appleboy/ssh-action — это действие, которое
      # позволяет выполнять SSH-команды на удалённых
      # серверах. Оно часто используется для
      # автоматизации развертываний приложений на
      # удалённых серверах через SSH с использованием
      # Jenkins, Travis CI и других CI/CD систем.
      - name: Deploy to FirstVDS via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |

            # завершить скрипт при ошибке
            set -e  

            # Перейти в домашний каталог
            cd

            # Клонировать репозиторий; удалить директорию, если она уже существует
            if [ -d "bibintoApp-frontend" ]; then
              rm -rf bibintoApp-frontend
            fi

            git clone git@github.com:force278/bibintoApp-frontend.git

            # Синхронизировать файлы
            rsync -avz bibintoApp-frontend/web/ /home/bibinto_front/

            # Запустить скрипт
            chmod +x front.sh  # сделать скрипт исполняемым, если это необходимо
            bash front.sh
            echo "Деплой успешен"
